### ISSUE TITLE
avast moving to quarentene

### ISSUE THREAD

**Issue by krustzer** [Mytherin/Tibialyzer#108]
hi, today 25/06 my antivirus Avast are moving tibialyzer for quarentene when i open the program.

anybody with this problem?

here's the pricture

http://i.imgur.com/BN2zYGK.png

thx

**Comment by KuerbisGnu** [comment]
quote
Mytherin:
"Virus scanners often have false positives, meaning they recognize innocent software as malicious. That is why the virustotal website has this disclaimer.

VirusTotal acts simply as an information aggregator, presenting antivirus results, file characterization tool outputs, URL scanning engine results, etc. VirusTotal is not responsible for false positives generated by any of the resources it uses, false positive issues should be addressed directly with the company or individual behind the product under consideration.
The entire reason virustotal exists is because virus scanners often have false positives, meaning that the output of a single virus scanner is not necessarily reliable. That link shows that out of the 56 virus scanners that were tested, 1 virus scanner thinks Tibialyzer is a virus. That means that it is very likely a false positive.

If you don't trust Tibialyzer, then you are free to look at the source code and compile it yourself. That way you can guarantee that Tibialyzer will not harm your computer."
