### ISSUE TITLE
Tibialyzer for Windows XP ?

### ISSUE THREAD

**Issue by ruppy69** [Mytherin/Tibialyzer#126]
Hello. Its not a problem just suggestion. What do you think about Tibialyzer for Windows XP SP3 ? Is it possible ? I think it would be really helpful for many players which are using XP. I used to using XP and really want try out your program.

**Comment by Mytherin** [comment]
The problem with providing XP support is that it only supports .NET 4.0. Since Tibialyzer uses .NET 4.5, a lot of code has to be rewritten so it can work on Windows XP, which will likely introduce more bugs and headaches. The other issue is that Tibialyzer is not a very lightweight program, and people running Windows XP likely use older PCs that might not be powerful enough to run Tibialyzer without lagging.

It's technically possible, but I'm not planning on doing it.  If you use a newer PC you should upgrade to Windows 7 because Windows XP is a legacy system. If you use a very old PC it likely can't handle Tibialyzer anyway.
