### ISSUE TITLE
'Ghosted' Monster loot appearing.

### ISSUE THREAD

**Issue by CuJo38** [Mytherin/Tibialyzer#128]
Not sure why, but I get 'random' loot messages show up from like a ghost log. If i am online at 13:45 I always seem to get
 '13:45 Loot of Necropharus: a book of necromantic rituals, 86 gold coins, a green mushroom, a necromantic robe, a soul stone, a clerical mace, boots of haste' 
It is from when I killed it, but this has been weeks ago. But its tied to that time stamp. I just got it again today, and I get other various commands pop up for me as well that are 'ghosted' as no one in any channel has said it, nor has it been said. Nor has that action happened. Necropharus was also killed on the beta version , where now im on the 1.3 version from scratch as it also randomly did a reset so i had to set my settings up brand new. Any ideas how to make these ghost messages stop?

**Comment by CuJo38** [comment]
i tried clearing the loot.txt file for now, will see if that works.

**Comment by CuJo38** [comment]
The issue continues to happen. 
[http://imgur.com/a/ofqrS](url)

**Comment by Mytherin** [comment]
I assume that for whatever reason that loot message keeps on getting placed into the memory of your flash client. I assume you aren't keeping the flash client open days on end, so for whatever reason CipSoft is sending this message to you every time. As long as it's in the memory of the flash client Tibialyzer will recognize it as a valid loot message, because there's no way it can distinguish between junk memory and actual messages it has to assume it's a valid message (otherwise valid messages could be missed). 

The good news is that Tibialyzer does look at the actual time on your system when scanning loot messages, so junk messages that don't occur at the current time will be discarded. The bad news is that apparently you will apparently get a popup everyday at 13:45. If you want to disable the popup you can set the value of Soul Stone and Boots of Haste to a lower value, so they don't trigger your popup condition, but I can't really think of another fix. It's just the flash client being weird.
