### ISSUE TITLE
Tibialyzer does not recognize "pile of grave earth"

### ISSUE THREAD

**Issue by gurka** [Mytherin/Tibialyzer#13]
As title. Looking at pile of grave earth does not trigger a popup window with information. I guess that the item is missing from the database?

> 22:07 You see 4 piles of grave earth.
> They weigh 3.92 oz.

Other items work fine, i.e.

> 22:07 You see 11 ghoul snacks.
> They weigh 15.40 oz.

**Comment by Mytherin** [comment]
Pile of Grave Earth is in the database. The reason the popup window doesn't trigger is that Tibialyzer only recognizes simple plural forms automatically. Simple plural forms meaning the letter `s` is appended at the end (e.g. `skull` → `skulls`). It doesn't recognize `piles of grave earth` → `pile of grave earth`. Thus instead of recognizing it as a plural Tibialyzer tries to search for the item `piles of grave earth` which does not exist. 

To deal with irregular plural forms, you have to tell Tibialyzer what the plural form is. This is done by adding the item to the `Database/pluralMap.txt` file, as I have done in this commit 59b1380e47ba565488edff83123d7564faa52ff2. 

I will leave this open because I want to extend Tibialyzers' ability to detect plurals, because `piles of grave earth` really should be automatically detected.

**Comment by benjaminkomen** [comment]
Some items already have their plural name on TibiaWiki, not all of them though. In TibiaWiki's loot parser some plural exceptions are listed as lootparser_p_words: http://tibia.wikia.com/wiki/Loot_Statistics/Code. You could copy that logic.

**Comment by gurka** [comment]
You could also use opentibia's items file. Just use sed or vim to extract
the lines, something like (in vim):

    %s/^.*name="\(.*\)" plural="\(.*\)".*$/\2=\1/g

https://raw.githubusercontent.com/opentibia/server/master/data/items/items.xml
Den 18 feb. 2016 9:23 em skrev "Benjamin Komen" <notifications@github.com>:

**Comment by Mytherin** [comment]
Thanks for your suggestions, I have extended Tibialyzers' ability to obtain the singular form in the following commit f80959a1f47211e3a93b7576d8763e695501f823. This should solve most issues with plural items not being recognized.
