### ISSUE TITLE
Addition of HUD

### ISSUE THREAD

**Issue by jameswinegar** [Mytherin/Tibialyzer#16]
Mytherin,

Do you think it would be reasonable to include a HUD similar to the flash client? I wouldn't mind working on this.

![HUD](http://i59.tinypic.com/112hh1e.png)

**Comment by EricArndt** [comment]
I would worry about the correctness of the overlay. Currently, I don't know if the starting values can be obtained from the server log messages. You said you were  considering implementing it. Did you have an approach in mind?

**Comment by Mytherin** [comment]
To implement this you would need to read the health/mana from memory, instead of just reading the server log messages. This is totally possible, but Tibialyzer does not currently do this. So the first problem would be finding out how to read the current life/mana of the player. After that, actually making the hud isn't that big of a problem.

**Comment by EricArndt** [comment]
I have no idea what would be necessary, but i suspect moving away from reading server messages could have a lot of benefits for all the features. Have you looked into this at all or have any idea how to approach this? I might be interested in tackling this.

**Comment by Mytherin** [comment]
Moving away from server log messages for other features would be difficult; the only thing that could replace server log messages would be intercepting the messages send to the client, which would involve figuring out how to decode them. You might be able to get this if you look at the source code of some bots, as I think they already do this. 

For just memory reading, I got a couple of tips from someone on reddit [here](https://www.reddit.com/r/TibiaMMO/comments/43k89u/introducing_tibialyzer_a_realtime_tibia_analyzer/cziyz76). The gist of it is that you need to figure out where in memory the value is (what offset it has) and then you can read it. This works fine with simple numeric values like 'health', 'mana' or 'position', but does not work for server log messages or strings because that it not just 'one value in one place' but 'many values in dynamically allocated locations'.

**Comment by EricArndt** [comment]
Seems like an interesting problem to tackle that would enable a bunch of features. Definitely some difficulties, but if I get some time this weekend I may end up taking a peek.

**Comment by jameswinegar** [comment]
Could get a lot of simple types of information with this some examples would be

- Max HP/Mana
- Current HP/Mana
- x,y,z positions
- % to skill increase
- current skill levels
- current exp

**Comment by EricArndt** [comment]
You mean if we read the values from memory instead of relying on server log messages?

**Comment by Mytherin** [comment]
Not instead of, but in addition to. But yes, we could get a lot more information by reading parts of the memory besides just the server log messages.

**Comment by gurka** [comment]
Could this affect the legal status of Tibialyzer?

**Comment by Mytherin** [comment]
As long as the HUD is implemented as an overlay like the other windows the legal status should not be affected, as we're just doing the same stuff we're already doing (reading memory and displaying information based on that in an overlay). I will send CipSoft an email to confirm, but I doubt the legal status of Tibialyzer would be affected by these changes.

**Comment by gurka** [comment]
IRCC they previously had problems with the overlay? They were afraid that people couldn't distinguish between Tibia's and Tibialyzer's windows? But maybe I misremember?

That's pretty strange anyway. Only someone new to Tibia could think that Tibialyzer's overlay belongs to the Tibia client, and a new player isn't going to use Tibialyzer the first time he/she plays...

**Comment by Mytherin** [comment]
The problem was that they didn't look at the actual program, they only looked at the screenshots. They thought that Tibialyzer was rendered onto the Tibia window (i.e. taking over the Tibia client's rendering context and rendering directly on the Tibia window), rather than the overlays being, well, overlays. I suspect the reason they thought that was because that's how bots that provide similar functionality do it. The overlays themselves aren't a problem.

**Comment by gurka** [comment]
Aha, I see. Then this feature shouldn't be a problem... unless they don't like that we (you guys) "steal" a feature from the flash client :-)

**Comment by villor** [comment]
This is a feature I would love! I started researching how to read values from Tibia and have created a little library that can currently be used to read current and max hp/mana. (https://github.com/villor/TibiaReader)

The hard thing was to find out the memory offsets, it can be done using Cheat Engine, but there is also a pretty good list over here: http://tpforums.org/forum/threads/6413-10-91-Addresses
They do change on every client update though...

**Comment by gurka** [comment]
> They do change on every client update though...

Yeah... that's what's good about Tibialyzer at its current state. You don't need to wait for Mytherin (or someone else) to update it when there is a new Tibia client version.

Just image the chaos if Mytherin goes on vacation for a few weeks (or whatever) and isn't able to update Tibialyzer if Cipsoft update the client. Of course someone else could update it, but unless they also upload the source code (or has access to this repo), you couldn't be sure that the updated Tibialyzer doesn't contains a keylogger or other nasty stuff.

**Comment by Mytherin** [comment]
> This is a feature I would love! I started researching how to read values from Tibia and have created a little library that can currently be used to read current and max hp/mana. (https://github.com/villor/TibiaReader)

Thanks for the help, villor! That's awesome and will save me a lot of time. With this implementing a HUD that displays current life/mana should be very easy. 

> Yeah... that's what's good about Tibialyzer at its current state. You don't need to wait for Mytherin (or someone else) to update it when there is a new Tibia client version.

When I use anything that relies on reading data from fixed addresses, I will not hardcode the fixed addresses in the code but I will read them from the settings file. That way when the addresses change because of an update you could change your settings file without having to recompile or change anything in the code. That should alleviate the issue somewhat.

**Comment by villor** [comment]
> Thanks for the help, villor! That's awesome and will save me a lot of time. With this implementing a HUD that displays current life/mana should be very easy.

No problem! I am happy to help :) 
The library has been updated to also find the player in the battle list to read the name and the position (x,y,z). Found XtrmJosh's reddit comment, it was of big help!

**Comment by Mytherin** [comment]
I just had this conversation with CipSoft.

### Request
> Hey CipSoft,
 
> I wanted to make an addition to Tibialyzer and I was wondering of the legality of this addition. Currently Tibialyzer only reads server log/chat messages from Tibia's memory, but I wanted to extend this to also read the status of the current character from memory (such as the characters' current life, mana, experience, level, position in the game world) in addition to the server log messages. Would this also be allowed?
 
> Thanks for your time,
 
### Reply
> Dear Mark,

> Thank you for your request.
> Yes, what you describe is also legal and will not jeopardise the Tibialyzer in any way. Those changes are allowed.

> Kind regards,
> Isolan
> Tibia Customer Support

Meaning that reading these values is allowed. I will work on implementing them when I have time (after I make some other changes I've been wanting to make). Alternatively, any one of you can work on implementing them and submit a pull request.

**Comment by villor** [comment]
That's good news! I have actually been playing around with this, trying to create a HUD overlay like the one for HP/Mana in the flash client. However I have not yet figured out how to get proper transparency for the controls in the windows form.

It may be better to draw it as an overlay using DirectX, there is a tutorial over [here](http://www.unknowncheats.me/forum/c/62019-c-non-hooked-external-directx-overlay.html) which explains how to do this without hooking anything into the client.

**Comment by Mytherin** [comment]
You can make transparent form windows, I've done so before. In fact, the Tibialyzer overlays used to be partially transparent in a very early version (but I removed this because it didn't look very good). I also prefer doing it using forms as overlays because I know that that is allowed already.

**Comment by villor** [comment]
> You can make transparent form windows, I've done so before.

Yes, I managed to make a fully transparent click-through form that overlays the whole window as well. I did this by overriding the OnPaintBackground method without calling its base, which prevents rendering the background. The problem seems to be the controls inside that form, for example a label will have a black background. But there is probably a way to fix that as well.

**Comment by Mytherin** [comment]
I think you need to do the same for any controls you add (such as labels). Create new controls that inherit from the base controls and override the OnPaintBackground method in the updated control, then add the updated control to the form. Not entirely sure though.

**Comment by gurka** [comment]
Couldn't you just set the TransparencyKey to some color (like purple, which
Tibia's sprites have IIRC), and then just set the same color as background
on the form and all its controls.

2016-03-01 20:52 GMT+01:00 Viktor Gustavsson <notifications@github.com>:

**Comment by villor** [comment]
> I think you need to do the same for any controls you add (such as labels). Create new controls that inherit from the base controls and override the OnPaintBackground method in the updated control, then add the updated control to the form. Not entirely sure though.

Unfortunately, that does not seem to work. I tried creating a control (TransparentLabel) inheriting from Label, with an empty OnPaintBackground-override. Still got a black background.

> Couldn't you just set the TransparencyKey to some color (like purple, which
Tibia's sprites have IIRC), and then just set the same color as background
on the form and all its controls.

Yeah, I have been playing around with this as well. I tried different combinations but nothing worked. Now I found out why though! The PInvokes I blindly copied from somewhere to make the window click-through messes with the transparency key of the window, there might be a way to fix that. I'll look into that! Thanks.

**Comment by villor** [comment]
Progress
![progress](https://cloud.githubusercontent.com/assets/7102243/13441276/9c7e84ac-dff6-11e5-9723-0d12944593af.png)

I followed gurka's advice and got it to work using transparency keys. Now I just gotta get rid of that shadow.

**Comment by gurka** [comment]
What shadow? You just have to put your 3d glasses on ;)

2016-03-01 21:45 GMT+01:00 Viktor Gustavsson <notifications@github.com>:

**Comment by villor** [comment]
> What shadow? You just have to put your 3d glasses on ;)

Well of course! "Tibialyzer - NOW IN 3D" :laughing: 

Jokes aside. I've had more progress!

![hud](https://cloud.githubusercontent.com/assets/7102243/13466614/fd303db4-e09a-11e5-900a-2662ac99526f.png)

I've done it in a [separate project](https://github.com/villor/TibiaHUD) for now. There are still some limitations though, for example semi-transparency wont work since it will just draw another shade of the transparency key (which will not be transparent, obviously).

The next step for me is to dive back into CheatEngine and see if I can find values for the position/dimensions of the actual game area. Right now the bars are just rendered in a fixed Y-position, so you will have to adjust the chat height for it to look good...

I also have an idea of detecting whether a dialog is shown, and hiding the HUD when it is, since the HUD is drawn on top of the dialogs at the moment.

There also seems to be some flickering, not extreme, but noticeable. Not sure if that is fixable with a high update rate like this (100ms polling rate atm). But it is crucial to have a high polling rate for the HP/Mana bars in my opinion.

I have also gotten some future ideas for new HUD-components:
* Cooldown bars (showing spell cooldowns/exhaustion/ring time left/magic shield time left etc.)
* Action bars (like in the flash client). The content of the bars could be read directly from the hotkey settings in memory. Even though clicking these would actually be sending input to the client, this may still be legal. I mean AutoHotkey is legal, as long as the commands only send a single key press. The same could probably be done for the action bars. These could also be combined with cooldown indicators.

**Comment by Mytherin** [comment]
Looking good! I had some issues with flickering forms before, you might be able to fix it [by setting WS_EX_COMPOSITED](http://stackoverflow.com/questions/3286373/flickering-in-a-windows-forms-app). I agree that they should definitely be refreshed frequently.

As for action bars, I'm not sure if it would be legal. I'd have to ask CipSoft again.

**Comment by villor** [comment]
> you might be able to fix it by setting WS_EX_COMPOSITED

Thanks! I think that fixed it. :)

**Comment by jameswinegar** [comment]
@villor: Can I suggest making the bars wider? I think would look better.

**Comment by villor** [comment]
> @villor: Can I suggest making the bars wider? I think would look better.

Sure can! But wider bars means more obstruction of the view, and since we don't have any semi-transparency at the moment it may be a bit too much.

I altered the width from 16px to 20px:

![hudwide](https://cloud.githubusercontent.com/assets/7102243/13469018/d10ff084-e0a5-11e5-80d8-a661444b443e.png)

I am also thinking of making it a little bigger (more spacing), so that a player surrounded by creatures can see all of them easily.

**Comment by Sythius** [comment]
I am so happy I yelled at James for long enough about wanting a HUD on C client (due to a corrupt database entry on CIP's side for my flash client). I had to switch to the c client to actually play, but I can die much easier without a HUD. I was able to use WASD movement prior to Tibialyzer using my keyboard, but it is more convenient through Tibialyzer. The next thing I have to worry about is using WASD but using ctrl to turn rather than shift to turn. If I switch to the two keys between one another, then it causes other issues such as a change in hot keys etc. Although OMG I just realized I might be able to use auto hot key to change shift WASD to ctrl WASD and then it may not change shift to ctrl for all hot keys etc. I am excited to get home and test this out now to test for potential discrepancies. Woot Woot.  Glad I decided to post now lol. Maybe I will think of other feature issues later and come up with my own solutions like that and if not, you guys can take care of it for me like the HUD issue. Also I am getting extremely excited for the HUD implementation. Once the HUD is in, you will definitely get some money out of my pockets. I can promise you that. Hopefully I can sneak some decent coin your way without upsetting the wife. Or I will get her in on this as well. Anyway, I wanted to say thank you all for this. We are now providing flash client features to the performance of c client which is amazing. Great job guys. Back to work for me so I will cease my rambling for now. Take care.

**Comment by Sythius** [comment]
Sorry I missed part of a sentence. I meant to say I am happy I yelled at James for long enough that you ended up launching your program and he brought it to your attention so you can all work on it. Great job guys.

**Comment by jameswinegar** [comment]
@villor: Any rough ETA when you will submit a PR for adding the HUD?

**Comment by villor** [comment]
Not any time soon I'm afraid... I have a lot to do right now in school, and I will be going away for a couple weeks to visit family. I probably won't be able to work on it until April. But feel free to continue where I left off if you want to :-)

**Comment by jameswinegar** [comment]
Just compiled it, looking at possible ways to enhance it :). I'll create a fork and try a few things. 

@mytherin, how do you want it packaged if to be included in tibialyzer? I'm not terribly proficient at C# (read zero experience), should I have it in a separate namespace and treat it as a separate application which can be wrapped inside of the tibialyzer winform in the long term?

**Comment by Mytherin** [comment]
I think it would be best to integrate the code with the rest of the Tibialyzer code rather than having it separated. I would put the code for reading the life/mana/other attributes from memory in the ReadMemoryManager ( `Managers/ReadMemoryManager.cs `). Then create a separate  `HUD ` directory and put the WinForm that holds the HUD in there, as we likely want to create other HUDs in the future. The rest of the Tibialyzer code just uses one namespace; I see no real reason to separate code into different namespaces at this point.

I would also create a new Tab on the main Tibialyzer for HUD settings (enabling/disabling the HUD, configuring where it would be placed, etc). It would be easiest if I would add this myself, although adding a new Tab isn't extremely complicated, you can check out this commit f1025626754f22b739e02ef3c9c82844bf814ae4 if you want to add a Tab yourself.

**Comment by damianmazurek** [comment]
Hey villor, how Can I use this HUD that you made? I downlaoded the source code but cannot run it cause i miss Tibiareaader, i bascily got 8 errors.

**Comment by jameswinegar** [comment]
You need to compile his other application which is the memory reader and use the dlls to compile the hud.

**Comment by EricArndt** [comment]
@Mytherin HUD has been implemented. This issue should be close.
