### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by EricArndt** [Mytherin/Tibialyzer#17]
This was discussed before, but I wanted to create an issue so there can be a consolidated place for discussion. From what I see there are a few different cases that can be addressed.

- Separate UI from actual code
- Break apart larger classes and methods
- Clean up anything that isn't used
- Reduce as much pressure on the GC as possible

All of these are pretty clear except the last one. If you look at the code in a profiler, you can see that the GC is being called pretty frequently. Since The current implementation is basically an infinite loop that runs as fast as possible (at the fastest setting), this is expected. However, there are plenty of opportunities to reduce this. One of the largest culprits is the creation of new strings that aren't very obvious. Strings are immutable in C#. This means that every call that produces modifies a string creates a whole new one (e.g. ToLower(), ToUpper(), and Substring()). Lots of these are pretty easy to get around, but it'll be a bit time consuming to go through and get them all.

You had mentioned that you were working on some refactoring, and it looks like there was some work done. What else is planned?

**Comment by Mytherin** [comment]
I will do some refactoring today. The main thing I'm planning to do is to split up the MainForm class into the following subclasses:

- `StorageManager.cs` - Handle the main database (`database.db`) and all operations on that database. There should be no SQL left outside of this class.
- `HuntManager.cs` - Handle everything related to managing hunts.
- `ReadMemory.cs` - Handle everything related to reading memory.
- `Parser.cs` - Handle everything related to parsing the server log messages.
- `NotificationManager.cs` - Handle everything related to displaying notifications.
- `CommandManager.cs` - Handle everything related to Tibialyzer commands.

After that, we will see what parts still need cleaning up.

**Comment by EricArndt** [comment]
I see that you made some good progress today. Like what I've seen so far :)

**Comment by Mytherin** [comment]
Alright, I'm done. I did a lot more than I initially set out to do but I'm pretty happy with the result. MainForm is a shell of its former self, with a meager 500 lines of code remaining in there. There's now about 20 different Managers that handle different functionality. In addition, I split up all the Tabs into different Forms in the Tabs directory, which means the hundreds of event handlers are now split up into readable chunks.

If you have any refactoring you want to do, you can go ahead now.

**Comment by EricArndt** [comment]
I'm seeing some strange behaviors like lots of duplicated notifications for loot. Have you noticed anything like this since your refactorings?

**Comment by Mytherin** [comment]
I haven't had any issues, but I've only tested the C Client. I will do some testing with the flash client this evening and check if it works there as well.

**Comment by EricArndt** [comment]
This seemed to be happening after a while in team hunts where lots of stuff died. There were up to 8 duplicated notifications for a single item drop. This was before some of your more recent changes. I'll continue to investigate, but I wanted to see if I was the only one to experience this issue.

**Comment by Mytherin** [comment]
Maybe 966da993ba91dbc6cae48353c5ade309c055c063 fixes it? Is the loot appearing twice as well, or is it only displaying multiple notifications?

**Comment by EricArndt** [comment]
What do you mean by loot appearing twice? In the loot log? I haven't dug in too much yet so I don't know if I can adequately answer.

**Comment by Mytherin** [comment]
I'm wondering if the loot appears multiple times in the loot@ window as well (in which case the same string is being scanned multiple times) or if it's just showing loot notification multiple times without scanning the same string multiple times.

**Comment by EricArndt** [comment]
I'll investigate and get back to you.

**Comment by EricArndt** [comment]
I can confirm that when it happens, multiple duplicated entries show in the loot window as well. This was happening even after your changes to look for `</font>` in the entire string. I got it to happen when hunting solo and killing things slowly as well. I can't consistently reproduce this so it's going to be a pain to fix.

**Comment by EricArndt** [comment]
I'm also pretty consistently getting missed loot messages. This is both in the notifications and the loot log.

**Comment by Mytherin** [comment]
You are using the flash client, right? Did this always happen or was it one of the recent changes to memory scanning that introduced this problem? Does commit f80959a1f47211e3a93b7576d8763e695501f823 have the same problem as well?

**Comment by EricArndt** [comment]
Yes, I use the flash client. The missed loot messages behavior isn't new, but the duplicated messages seem to be new. Look messages seem to be lost as well. I'm running on the fastest scan speed.

**Comment by Mytherin** [comment]
And this only happens after running the client for a while? I haven't run into either of these issues but I haven't done any testing longer than maybe 30 minutes on the flash client.

Maybe an idea would be to also scan loot messages with `</font>` in them and skip all duplicate messages (because there will be a lot of them). The problem with that would be that if two different creatures drop the exact same loot twice in the same minute. This shouldn't be common for high level creatures but will be common for creatures like deer or wolves. 

Not sure how else to solve it, especially since it's so inconsistent.

**Comment by EricArndt** [comment]
This seems to get worse as the client runs for longer. What do you mean by skip loot messages with `</font>` in them? I thought that was already done in 966da99. I've had friends using the stand alone client complain of missed loot messages as well. They were using the latest release (tag v1.1.0). This is going to be a pain to track down. I'll keep looking at it and I just want to bring up awareness of the issue. Just for completeness, here are the behaviors I'm seeing.

- Loot/look messages are being completely missed.
- Loot/look messages show up after a long delay. Sometimes 5+ seconds.
- Look messages take a long time to come up, but are near instant on subsequent tries.
- Loot messages are duplicated. (This might be resolved)
- Performance seems to degrade with time and more incoming server messages.

**Comment by EricArndt** [comment]
The whitelist doesn't seem like it ever shrinks. The values only get set to -1 later. I did some brief investigation and it seems like this just continued to slowly grow. Is this intended?

**Comment by Mytherin** [comment]
My idea was to **not** skip the loot messages with `</font>` in them, i.e. the opposite of what that commit is doing. However, if we do that (scan those messages as well), we would need to eliminate duplicate messages, because there will always be multiple duplicate messages. It might solve both issues though (as we would probably find at least one copy of a message if there are multiple, and duplicate messages would not be possible). However, it would introduce some new issues ('legitimate' duplicate messages would be ignored).

**Comment by EricArndt** [comment]
If the issue is isolated to the flash client, then that's something to consider. I have had at least one friend that uses the stand alone client say that loot is missed as well. I'll need to verify, but if that is the case, then I would guess that the issue is in how we determine that a message needs to be acted upon. I wonder if it has something to do with the count comparison for handled and unhandled messages. I can't say I fully understand how this is done and haven't had a good opportunity to dig in. Where does this sit in your list of priorities? In my opinion, it should be pretty high up there as fixing this could require large architectural changes that could affect future features.

**Comment by Mytherin** [comment]
It doesn't really matter where it sits in my list of priorities, I can't fix it if I don't know the cause of the problem, and since it's not reproducible for me I can't investigate it either. 

I seriously doubt it has anything to do with the way messages are handled. That code hasn't changed in a long time and has never been a problem. It's way more likely the messages are simply never found, or they are found multiple times in memory, which leads to strange behavior. The flash client in general has very strange memory management, which causes all sorts of issues.

As for missing loot messages on the C client, I'm curious which loot messages are being skipped. I know of a bug that skips any creatures that drop Jalapeño peppers because the unicode character isn't parsed correctly, leading to Tibialyzer not recognizing the item, leading to Tibialyzer skipping the message. Similar issues might occur in older versions with certain plural items not being correctly recognized (although that should be fixed now). I doubt that has the same origin as the flash client issues.

Alternatively, it might be caused by too slow scanning, although this is unlikely. The scanning would have to be extremely slow to find loot messages 'too late' to process them (as Tibialyzer looks at messages at most 3 minutes in the past, and scanning takes 150ms~ on my machine).

**Comment by EricArndt** [comment]
I'm not requesting that you fix it, I was wondering if you were investigating the issue. Any information about this would be helpful. I'm trying to find out if this issue is only on the flash client or if there are know issues for both clients that could lead to this behavior. Like I mentioned before, I'll keep investigating and report anything useful I find.

**Comment by Mytherin** [comment]
Alright. I only just read your list of issues and I do know the causes of a couple of the issues that are not the duplicate/missing loot ones, so I will expand on those a bit.

> Loot/look messages show up after a long delay. Sometimes 5+ seconds.
> Look messages take a long time to come up, but are near instant on subsequent tries.

These are the same issue, and this has to do with the modified scanning algorithm. There are two threads, one searches for chunks to scan and the other scans the found chunks. If this delay happens, that means a loot/look message popped up in a chunk that the 'active' thread isn't scanning. Since the other thread scans much more slowly (to not consume too much resources) finding the message in an 'inactive chunk' takes a long time. This isn't really a problem with the C client (in my experience) because messages appear in inactive chunks very infrequently, and the C client has much fewer memory chunks than the flash client. It might be a better idea to use a different scanning algorithm for the flash client altogether, if this happens often. 

Note that the alternative to this is scanning the entire memory all the time. This will lead to significantly slower average response time, but will prevent these slow spikes.

> Performance seems to degrade with time and more incoming server messages. 
Possibly also related to the new scanning algorithm with the flash client. If too many chunks get added to the whitelist, and they are never cleared by the flash client, then more and more memory will get scanned. This could maybe be solved by removing chunks if they only contain old messages (messages older than 3 minutes), as these aren't used anyway. That would involve updating the SearchChunk method to return whether or not the chunk contains any new messages, rather than just returning whether or not it contains any message at all.

> The whitelist doesn't seem like it ever shrinks. The values only get set to -1 later. I did some brief investigation and it seems like this just continued to slowly grow. Is this intended?

This is simply to avoid having to lock the whitelist (since there is another thread that is adding items to the whitelist). It would grow but I would think extremely slowly. Unless there's thousands of memory chunks being added by the flash client, it shouldn't be too much of a problem, but it isn't a very clean solution. I might replace it with properly locking it and removing the entry instead of setting it to -1, but I think this doesn't really have any impact.

> Loot/look messages are being completely missed.

This could be what I said (Tibialyzer doesn't recognize the item looked at/one of the items dropped). It could also be a flash client specific issue, where maybe the strings aren't null terminated so they aren't found.

> Loot messages are duplicated. (This might be resolved)

No idea, I think this has to be a flash client specific issue relating to possibly corrupted/unused memory being scanned? This can really only happen if the same message occurs multiple times in memory.

**Comment by EricArndt** [comment]
Thanks for the info, that will definitely help me out. I just wanted to comment that the missed look messages are definitely not entirely related to unrecognized items. Know items that have worked before just fail to come up sometimes.

**Comment by EricArndt** [comment]
Just to give an update, I believe I've made some progress on this, but I need to do some extensive testing that I just haven't had time to do yet. Most of these performance concerns are specifically related to the flash client solely because of the much larger memory footprint it has. It just takes longer to scan more memory. I've done my best to try to speed this up as much as possible. The ideal goal would be to determine which blocks will never be relevant and can be skipped altogether. I have made no progress on that front though. This is only related to the full scan that whitelists blocks for the other scanning thread to use. Once a block has been whitelisted, things are nice and snappy. My current implementation doesn't try to un-whitelist any blocks like your current implementation does. This seems fine, but I was wondering why you chose to do this in the first place? The whitelist doesn't seem to get very large at all.

**Comment by Mytherin** [comment]
Glad to see you are making progress. The reason I un-whitelisted blocks was because it intuitively made sense to remove useless blocks, I never did any testing on if this was necessary or even counter-productive (it could be that  block does not have any useful strings for one scan iteration, but they might be added again later). It could very well be that not removing blocks from the whitelist is a better idea.

Discovering which blocks will never be useful is challenging, possibly you could look for some patterns in the whitelisted blocks (such as e.g. size) and go from there?

**Comment by EricArndt** [comment]
Size might be a good indicator. I'm considering looking at the structure of the block, but that will be challenging. I just want to be careful since excluding a block could mean things get missed.

**Comment by EricArndt** [comment]
As this conversation had drifted into behavioral changes instead and the refactoring can be called done, I'm closing this issue.
