### ISSUE TITLE
Exp/h

### ISSUE THREAD

**Issue by jameswinegar** [Mytherin/Tibialyzer#20]
Probably want finer resolution than 15 minutes, I think Tibia's internal calculation uses 5 minute blocks for estimating the next hour.

**Comment by Mytherin** [comment]
My calculation matches Tibia's calculation exactly, as far as I'm aware. Everytime I check Tibialyzer's experience per hour and Tibia's experience per hour they are exactly the same.

**Comment by EricArndt** [comment]
What would be the reason for this change? Have you notice the values are inaccurate? We don't necessarily need to do exactly what tibia does if there is some benefit to deviating.

**Comment by jameswinegar** [comment]
It is a better estimate to the current rate than 15 minutes. The overhead
for the calculation is very low as well.

This was my thought more-so than anything else. When I am hunting I want to
know how I am doing now rather than over the last 15 minutes.

On Mon, Feb 29, 2016 at 2:43 PM, Eric Arndt <notifications@github.com>
wrote:

> What would be the reason for this change? Have you notice the values are
> inaccurate? We don't necessarily need to do exactly what tibia does if
> there is some benefit to deviating.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mytherin/Tibialyzer/issues/20#issuecomment-190378644>.
>



-- 

James York-Winegar

jameswine@gmail.com

(931)-220-1962

**Comment by Mytherin** [comment]
I'm not sure if better estimate is the correct term. The smaller that the time window gets the more volatile it is. If we're going to change the experience per hour calculation I think a different formula should be used, rather than simply lowering the time interval.

Maybe the new [experience graph](http://i.imgur.com/FhtgnoN.png) could also help you in determining how you're doing right now.

**Comment by EricArndt** [comment]
If anything I could see wanting to go the other way and have intervals that you manually reset. This would allow for you to see the total exp/hr with refils and travel time included. During the hunt, it might appear that one spot is better, but time lost due to walking to it may make a closer spot better.

**Comment by jameswinegar** [comment]
Are the overlays able to be interacted with? We could provide a slider for that part and have it be used to see different bin sizes? Choosing granularity as they wish.

**Comment by Mytherin** [comment]
I added a different experience per hour computation that can be selected in commit 4928b9b24079b9c4942e63066b73f1f8d8c54788. It weights recent experience gains more than later experience gains, meaning it reaches the 'true' experience per hour faster while still being stable.
