### ISSUE TITLE
Legal Issues with application

### ISSUE THREAD

**Issue by GalLuvton** [Mytherin/Tibialyzer#38]
Hey there Mytherin.
First, I have to say this project is amazing. I love the work you put into this, and I am learning quite a lot from reading your implementation.
I am a vice leader in a major guild, and I really wish to spread word of your tool here, but I have some concerns:
- Why is there a AutoHotKey built into your app? AutoHotKey could easily be used to write bots (although simple ones), or have manasitting players. You went so far to show that your app is within legal bounds, and then you added this aspect to it.
- What is the point of 'pathfinding' database? It this a tool to mark a path from point A to B, or walk it? Pathfinding is one of the keystones for creating a bot, and I worry this might be used to create bots (when combined with AutoHotKey and read mana/hp values).

Is it OK if I fork your work, remove the AutoHotKey part, and link that to my guild members? I will not touch the index page, so it still shows it is your project (and has the donation button).

If there is any other way to contact you aside from questions here, I would love to know about it.

Again, thanks for some amazing work!

**Comment by Mytherin** [comment]
The AutoHotkey integration is there to make remapping hotkeys easier for players and to provide the overlay that makes remapped hotkeys easier to use. AutoHotkey is completely legal, and has been confirmed by CipSoft to be legal, AS LONG AS you only ever do a 1:1 mapping (i.e. pressing one key combination maps to one other key combination) without any delays or loops or timers. 

AutoHotkey can be used to make bots, but that's up to the players'  themselves. If a player uses AutoHotkey to make a bot, they are violating the rules. That has nothing to do with Tibialyzer or the legality of Tibialyzer. 

The pathfinding database is used for marking paths from point A to B and showing the route to players. Currently it's used for showing directions to NPCs and to Hunting Places, although I would like to extend it to also show guides for quests. So it would tell you where to walk, and display the exact route you need to walk, during each step of the quest. Kind of like quest helper addons in World of Warcraft if you are familiar with those. 

You could use the pathfinding as a basis to make a bot, but then if you wanted to create a bot there are Tibia Bots on Github already. If you want to make a Tibia bot you would be way better off cloning an existing Tibia bot rather than starting from Tibialyzer. It's not like pathfinding is particularly difficult, either.

And absolutely, feel free to fork the source code, and modify it in whatever way you want.

**Comment by GalLuvton** [comment]
Thanks for the reply!
I know its all too easy to find code for tibia bots, but its one thing to look it up yourself, and another for me to link guildies with something that might draw them in :p
I understand your explanations, and accept them completely.

Thanks again for an amazing project!
