### ISSUE TITLE
Counting used arrows/bolts.

### ISSUE THREAD

**Issue by kugrjado** [Mytherin/Tibialyzer#41]
Hi, I'm not sure if it's my fault or a problem related to Tibialyzer.
When I hunt creatures I can see my waste by using either _waste@_ or _summary@_ command, while it shows my used runes and potions corectly, I can't make it to work with used ammunition.
I tried looking at my ammunition on hotkey to get a message like '**Using one of xxx crystalline arrows...**' before the hunt, and after the hunt, but Tibialyzer doesn't count them corectly.

This is the sample scenario that shows my problem:
1) I use my hotkey to see how many arrows I have (**Using one of 1000 crystalline arrows...**).
2) I hunt for some time and use let's say 250 crystalline arrows.
3) I use my hotkey again to see how many arrows I have left (**Using one of 750 crystalline arrows...**).
4) I use _summary@_ or _waste@_ command to see my waste.
5) I see I have used only 2 crystalline arrows.
6) I drop 1 crystalline arrow on the ground.
7) I use my hotkey again to see how many arrows I have left (**Using one of 749 crystalline arrows...**).
8) I use _summary@_ or _waste@_ command to see my waste.
9) I see I have used only 3 crystalline arrows.

**Comment by Mytherin** [comment]
Tibialyzer waste doesn't work with ammunition currently. The way Tibialyzer counts items is by looking at individual usages, which works well for potions and runes (because you have a Using... message for every potion you use), but doesn't work with arrows in the way you described unless you use your count hotkey after every shot you fire. 

I'm not sure how ammunition could best be tracked. An option would be to allow the user to register the usage themselves, or have them use the arrows at the begin/end of the hunt, but I think the best way would be to read the equipped ammunition from memory and then register when an arrow disappears from the ammunition slot. However, I don't know how to read equipped items from memory currently.

**Comment by kugrjado** [comment]
IMHO use the arrows at the begin/end of the hunt would be the best temporary solution if it's possible to implement it.

**Comment by Mytherin** [comment]
Yea, should be easily possible. I'll work on it later today.

**Comment by GalLuvton** [comment]
I could provide with the code to read ammunition, if you need it.

**Comment by Mytherin** [comment]
You mean read the currently equipped ammunition from memory? That would be fantastic.

**Comment by GalLuvton** [comment]
Reading currently equipped ammunition count is just likr reading HP or MP (without the xor)
Address for that value is tibiaBase+0x773E8C
Read 4 bytes from that address to get the current amount (0 means no item equiped to that slot).
I really diden't check to see what happens if the item there is not stackable (magic light wand, or the like), but if you add 4 to that address, you can read the item ID, and validate it as a stackable ammo

**Comment by Mytherin** [comment]
Is there a mapping available from item id -> item name so I can figure out which type of ammunition is being used?

Another issue would be ammunition that is not in the ammunition spot, like spears or assassin stars. Do you know the memory address of the weapon slot as well?

And a separate issue, but I would also like to track ring/soft boots/amulet usage, as this is currently not supported. Do you know the memory addresses of those equipment slots as well?

**Comment by GalLuvton** [comment]
The full item ID list could be found online, I could look for it later (in class at the moment).
As to rings, amulets: the game does not track the item count (since it doesn't need to display it). There is no way to get that amount without "looking" at the item (as far as I know).
As for spears, I could find it for you once im home, shouldn't be a problem.

**Comment by GalLuvton** [comment]
For now, you can test to see if these IDs are game IDs (pretty sure they are).
If not, let me know.
http://tibia.wikia.com/wiki/Item_IDs

**Comment by Mytherin** [comment]
I'm at work, so I won't be any testing for at least a few more hours either.

For rings/soft boots, it would be sufficient to check if a specific item is in the slot. For example, for life rings, you could check every second "is there a life ring in the slot". If there is, you can add 1 second to the 'used life ring time'. Same with soft boots and other rings.

Amulets would be more difficult to track, but then I don't think amulets are used that often in hunts anyway so it isn't that big of a deal. What you could do is check if a consumable amulet is equipped, then if it isn't equipped anymore count it as "consumed", but then that doesn't work if the person simply switches the amulets out. So that's not a very good solution. I think just not checking amulets is fine, since they are so rarely used compared to ammunition and soft boots/rings.

Thanks for the help so far, by the way!

**Comment by SirIkarth** [comment]
The Flash client is actually sent a full list of all items and the amount your character has in their inventory, including within any containers be it opened or closed, to display the item count on the action bars. This list is also sent to and stored by the standalone client as well, so you could use this list to determine usage of supplies (including runes and potions) with higher accuracy which will also work for "full" amulets since their count will decrease by 1 when destroyed (also when moved outside of your inventory altogether but that's a small issue). In my opinion this is the best way to track supplies and how I've been doing it in my own HUD program, however it is more complicated especially since the list is stored within a STL vector so you would need to determine not only the item data structure and its memory layout but also the data structure and layout for the STL vector and finding the address after an update is probably somewhat more difficult as well.

**Comment by GalLuvton** [comment]
Actually, I would quite like to have this list in my tool aswell. Care to explain how to locate it? Is it in a static address?

**Comment by GalLuvton** [comment]
Regarding my comment:
The ID page I gave you checks out, all IDs there are valid.
The other addresses you requested:
weapon count: base+773F0C
weapon ID: base+773F0C+4
boots ID: base+773ED0
amulet ID: base+773F90
ring ID: base+773EB0

Regarding the arrows (and all items really): if an item slot is empty, the ID is 0. If the item is non-stackable, the count is 0, but the ID is valid.

**Comment by SirIkarth** [comment]
Yeah there's a static address which is a pointer to the vector structure. To find it I use OllyDbg and first find the packet parser loop, I normally do this by searching for all switches and navigate to the one I know is right but without knowing that you can search through referenced text strings with "packet" in it looking at the referenced code for something that looks like a parser loop/switch case. From there I look for the 0xF5 switch case which I know is the ID for the inventory list packet that I initially determined from decompiling the Flash client (there's a switch case in the standalone with string constants you could use too, just keep in mind the value in the switch is -10 of the actual ID), then it's just a matter of going into the 0xF5 packet function and looking through its code (including functions it calls) to determine how the items data is copied from the packet and looking at the static addresses within instructions (before and after the loop being a good place to check).

You could find the address with a memory viewer/editor too if that's your tool of choice. I haven't done it like this myself but I think the best idea here would be putting X amount of Y items in your character's backpack then logging onto them on a freshly opened client and make sure you don't open any backpacks, then memory search for the item ID of Y with the value X nearby. You will now be somewhere in the vector's data array, you will want to find the address of the first element so backtrack until you find that (this element won't necessarily have an actual item ID) and once you have that address you can search for a pointer to it which should now be somewhere in the vector's structure (you might get some false hits if the address is still somewhere on the stack). Now the vector is a C++ class object with a virtual function table whose pointer is stored at the start of the structure so backtrack a bit in memory to find a pointer to near the client's code, this should be start of the vector so search for a pointer to that address which should now be the static address you want.

I'm sorry if any of that sounds confusing and vague, I'm not really the type to hand over the exact detailed steps of how to do things like this but rather prefer give hints and ideas to help you figure it out so you have a better understanding of it and adapting to potential future changes. And you definitely seem knowledgeable enough to figure it out from what I've given. Oh and one small other hint is the vector structure doesn't contain the explicit size or number of elements but uses pointers to various points of the data array along with the item structure size to calculate these.

**Comment by GalLuvton** [comment]
> within any containers be it opened or closed

> and make sure you don't open any backpacks

Those kind of contradict. Do you you mean it stores data about all containers opened, even if they were later closed?

**Comment by SirIkarth** [comment]
The list is of all the items on your character, that is everything you have equipped and everything you have in both unopened and opened containers.

The "and make sure you don't open any backpacks" comment was just some advice if you're searching for the full inventory vector address with a memory editor to minimise the hits for the item ID. If you have opened the backpack containing your search item you will get a result inside the items list for one of the opened containers (a vector inside a container structure inside a red-black tree) which could mess up your results, so starting a new client and not opening any containers will limit the results and make it that much easier to locate the right vector.

**Comment by GalLuvton** [comment]
@kugrjado Please close this issue as it has been implemented
