### ISSUE TITLE
Damage counter

### ISSUE THREAD

**Issue by renegh23** [Mytherin/Tibialyzer#5]
New ferumbras gets tracked as a player instead of creature  maybe its because how its wrote

14:23 xxxx loses 23 hitpoints due to an attack by Ascending Ferumbras.
14:26 You lose 370 hitpoints due to an attack by Ferumbras Mortal Shell.

and would be awsome to filter the damage ive received only or x or y player received

**Comment by Mytherin** [comment]
The reason for that is because the creatures [Ascending Ferumbras](http://tibia.wikia.com/wiki/Ascending_Ferumbras) and [Ferumbras Mortal Shell](http://tibia.wikia.com/wiki/Ferumbras_Mortal_Shell) are not known as creatures to Tibialyzer. Tibialyzer gets all the creature information from the tibia wikia, and apparently these two creatures are not present on tibia.wikia.com or have no image associated with them. If you want to fix this issue, you can do so by contributing to [tibia.wikia.com](tibia.wikia.com) and adding these creatures.

**Comment by benjaminkomen** [comment]
Creatures now have pages and placeholder images.

**Comment by Mytherin** [comment]
I have updated the database in commit 02ece8b71eb081eff8591fa65b929874e713752c to reflect the latest state of tibia wikia. So now Ascending Ferumbras and Ferumbras Mortal Shell are creatures, which should resolve this issue. I also updated the latest release, which you can download from [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.1).
