### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by MisterJak** [Mytherin/Tibialyzer#52]
I've had this display (not so big) problem since 1.2, where the left side of the window is covered by the tabs. Is there a way to solve this?

![display 1](https://cloud.githubusercontent.com/assets/18322844/14485941/8f28f212-015a-11e6-90fa-2a77ead7f4cf.png)
![display 2](https://cloud.githubusercontent.com/assets/18322844/14485940/8f28dc28-015a-11e6-8228-337c8a86ef97.png)

**Comment by Mytherin** [comment]
I really think this is related somehow to your .NET installation (or maybe even your Windows installation). Try installing a newer version of .NET, like [.NET 4.61](https://www.microsoft.com/en-us/download/details.aspx?id=49978).

**Comment by MisterJak** [comment]
Hi Mytherin, I installed .NET 4.61 but that didn't help...Any other possible solution? Thanks!

**Comment by Mytherin** [comment]
I have no idea what the problem could be. The controls aren't offset enough to the right, which is weird considering they're offset by an absolute amount. It seems like all dynamically positioned elements are just shifted by about 30 pixels to the left. I have no idea why that would happen. My guess is that it's a problem somewhere in your Windows installation,  since you're the only one that has this issue. Reinstalling Windows will likely fix your problem. Is it only the main Tibialyzer window and the creature@ tabs that have this problem, or do more tabs have the issue?

**Comment by GySterr** [comment]
Mytherin, can you just make update with full screen of Tibialyzer or something like that? I have the same problem.

**Comment by Mytherin** [comment]
Interesting, if multiple people have this issue it's unlikely to be a corrupted windows installation. I think it might be related to absolute values used in the interface somehow. I've added an update using relative values instead of absolute values [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.2-beta), can you check if that solves the issue?

**Comment by GySterr** [comment]
Wow, that works really much better so far.  http://scr.hu/0sgu/03mh6
Only this Notifications are bugged:
 http://scr.hu/0sgu/zv0s3
http://scr.hu/0sgu/9g79g
Rest looks great. :)

**Comment by GySterr** [comment]
Can you add to Loot Notification Profit too? I mean Total Value - Used items = Profit :)

**Comment by MisterJak** [comment]
Seems like this display issue was fixed with the beta release. Great work! :)

**Comment by hadewych** [comment]
new update? :D
