### ISSUE TITLE
CPU Ussage!

### ISSUE THREAD

**Issue by Edward2103** [Mytherin/Tibialyzer#54]
Im having troubles with the last update of this software, before the update i use tibialyzer and everything was ok, since the last update everytime i use it the cpu ussage is going to 90-100% CPU only for the tibialyzer, any clue about what is happening?

**Comment by Galarzaa90** [comment]
The same has happened to me, but seems to be random. Hunting at the same place on 4 occasions (so about same kill rate, similar loot), the last time Tibialyzer started lagging and I saw it was taking close to 100% of my CPU.

Notification popups started slowing down, sometimes getting stuck before getting in position. Health HUDs would update at random.

![sshot-2016-04-14- 23-14-19 allan-pc](https://cloud.githubusercontent.com/assets/12865379/14565215/dd23d68c-02de-11e6-8c0e-991bf8f76e23.png)

Eventually, it would stop counting kills, and then count all the kills at once. I got this when I was leaving:

![sshot-2016-04-14- 23-19-29 allan-pc](https://cloud.githubusercontent.com/assets/12865379/14565261/0e68c176-02df-11e6-8a22-7855bcf244a1.png)

 I tried playing with the scanning speed slider but it wouldn't reduce the CPU usage and it wouldn't fix the lag (Note: The tibia client wasn't lagging).

This had happened to me before on previous versions, but I was using two monitors that time and I thought that was the reason (I wasn't even hunting, just doing a quest and killing some mobs)

**Comment by EricArndt** [comment]
Which update did you start seeing this?

**Comment by Mytherin** [comment]
What scanning method are you using?

**Comment by Galarzaa90** [comment]
@EricArndt Since commit [7c75d87](https://github.com/Mytherin/Tibialyzer/commit/7c75d87946e821ed9c7129ec7eba2fa7a745d10c)

@Mytherin Internal tab structure

**Comment by Mytherin** [comment]
It's likely not related to the scanning, probably an infinite loop somewhere in the notifications handling. Since it seems you're showing notifications on every drop that might be why you experience the issue more often. I'll have a look there and see if I can find anything.

**Comment by Galarzaa90** [comment]
Yeah, I had my gold/oz ratio for popups set to 200 so Asuras trigger it a lot, I increased it. But the other time this happened just doing some Ice Island mission, where I wouldn't get as many popups.

**Comment by Galarzaa90** [comment]
Just some info of my struggle during tonight's hunt, don't know if the info helps in some way:
Raised my gp/oz ratio to 500 to reduce notifications, hunted for 40mins without problems and then it started lagging more and more, until it stopped tracking creatures and updating HUDs.

Tried using clear@ and it unfroze everything, but as soon as I killed a creature, it would freeze again. Sometimes hiding and showing HUDs again would fix them, sometimes only one would get stuck.

Sometimes the clear@ command would stop working, only autohotkeys commands would work. I raised value and gp/oz triggers to 10000. That helped a bit, HUDs were updating but kills were stuck. I would suddenly get a bunch of notifications (from stuck kills).

I finally decided to close and reopen Tibialyzer in the middle of the hunt. The problem was solved, no more high CPU usage, no more HUD lag or stuck kills, but my notifications were pretty much disabled...

**Comment by Mytherin** [comment]
I've revamped the code that is responsible for refreshing notifications/HUDs/popups. Can you check if the latest [beta](https://github.com/Mytherin/Tibialyzer/releases/download/1.2.2-beta/Tibialyzer.1.2.2-beta.zip) does anything to fix this issue?

**Comment by Edward2103** [comment]
let me try it and i will tell u if it works!

**Comment by Edward2103** [comment]
a couple of minutes working and everything is going excellent :D great job!!

**Comment by Edward2103** [comment]
![ss 2016-04-16 at 06 14 38](https://cloud.githubusercontent.com/assets/18472788/14584075/bdd6cc9a-03ff-11e6-8077-f1f7c1788a32.jpg)


works for some time, but now it get this cpu ussage... mmm but its like getting up and down!

**Comment by insectx89** [comment]
Not works good. I standing in DP, no hunt, and cpu ussage growing to 60% i have one of the best available CPU on the world (i7-6700HQ)

**Comment by insectx89** [comment]
Not works good. I standing in DP, no hunt, and cpu ussage growing to 60% i have one of the best available CPU on the world (i7-6700HQ)

**Comment by Mytherin** [comment]
@Edward2103 @insectx89 Can you provide some more information? Like what HUDs/Notifications you have open when this is happening and how long Tibialyzer has been running before this happens?

**Comment by insectx89** [comment]
i need to review it again because when i restarted the application all works fine (1% of CPU is loaded), it is strange... i let you know when problem appear again.

**Comment by TeamRedBeard** [comment]
So, I have been live streaming Tibia

I noticed I kept getting "High CPU usage warnings" and that never happens when I stream, the only change I made this time was using Tibialyzer
- I am running Windows 10 64 bit with 16 GB Ram, running an i7-3820 @ 3.4ghz
When I checked task manager I was at 100% CPU, and 50% of it was Tibialyzer (I was running my stream at this time which was using like 15-25%)
- Tested without streaming and still eats up CPU

Please let me know when there is a fix possibly, everybody on my live stream was loving the loot menu that I had shown

**Comment by EricArndt** [comment]
@Mytherin Should have issues resolved. Check out my PR.

**Comment by Mytherin** [comment]
@insectx89 @TeamRedBeard @Edward2103 @Galarzaa90 I've updated the [beta release](https://github.com/Mytherin/Tibialyzer/releases/download/1.2.2-beta/Tibialyzer.1.2.2-beta.zip) with the fix by @EricArndt, check if that fixes the problem.

**Comment by Galarzaa90** [comment]
Sorry, I wasn't able to test it until last night.

I tried the same place, last night and tonight, and so far everything is running smooth, and the CPU usage seems to be back to normal.

**Comment by EricArndt** [comment]
@Mytherin Can this be closed?
