### ISSUE TITLE
Chrome request

### ISSUE THREAD

**Issue by TheLateTes** [Mytherin/Tibialyzer#83]
Hello, thank you very much for putting this project together. 
If it is possible would you or one of your supporters be able to get the Chrome extension/addon working? I have tried using Firefox but I frequently have delayed input issues while using Firefox specifically. 
I would be willing to put up a bounty if anyone was willing to help with this, I was thinking around $20 (could also transfer tibia coins), which I hope isn't undervaluing anyone's time.
If this isn't the appropriate forum for such requests my apologies I'm new to Github.
Thelates - Amera

**Comment by Mytherin** [comment]
I added Chrome Flash Client support to the latest beta release, which you can download [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.2-beta). No need for any donations, I don't really like taking people's money because it makes me feel obligated to help resolve their issues even more than I already do.

I recommend enabling "Skip Duplicate Loot" and "Skip Duplicate Commands" in the "Settings" tab to avoid duplicate messages causing too many issues. It's not great, and for the best Tibialyzer experience I still recommend using the standalone client, but it should work reasonably well.

**Comment by TheLateTes** [comment]
Thank you very much, it works like a champ on Chrome.
