### ISSUE TITLE
Done

### ISSUE THREAD

**Issue by Tarriz** [Mytherin/Tibialyzer#95]
the issue has been taken care of :3

**Comment by Mytherin** [comment]
Virus scanners often have false positives, meaning they recognize innocent software as malicious. That is why the virustotal website has this disclaimer.

> VirusTotal acts simply as an information aggregator, presenting antivirus results, file characterization tool outputs, URL scanning engine results, etc. VirusTotal is not responsible for false positives generated by any of the resources it uses, false positive issues should be addressed directly with the company or individual behind the product under consideration.

The entire reason virustotal exists is because virus scanners often have false positives, meaning that the output of a single virus scanner is not necessarily reliable. That link shows that out of the 56 virus scanners ran, 1 virus scanner thinks Tibialyzer is a virus. That means that it is very likely a false positive.

If you don't trust Tibialyzer, then you are free to look at the source code and compile it yourself. That way you can guarantee that Tibialyzer will not harm your computer.

**Comment by Tarriz** [comment]
I am not smart enough to see any kind of informations in the source code but I'll take your word for that, just wanted to be sure that for example someone somehow didn't switch the links or whatever.
Thanks dad for your hard work :D

**Comment by mathiasbynens** [comment]
@Tarriz Please don’t remove your original post like that.

**Comment by Tarriz** [comment]
@mathiasbynens Sorry, I felt like I was accusing Mytherin stuff just because I lack the knowledge to figure stuff out on my own, didn't want to make the software look bad because of that

**Comment by mathiasbynens** [comment]
Other people might have the same problem, and then it would be useful if they found this page rather than creating duplicate issues.
